apiVersion: v1
description: ElastAlert is a simple framework for alerting on anomalies, spikes, or other patterns of interest from data in Elasticsearch.
name: elastalert
version: 1.5.0
appVersion: 0.2.4
home: https://github.com/Yelp/elastalert
sources:
- https://github.com/jertel/elastalert-docker
- https://github.com/Yelp/elastalert
maintainers:
  - name: jertel
    email: jertel@codesim.com
  - name: olemarkus
    email: o.with@sportradar.com
engine: gotpl
